Support of Polkadot Addresses
dfinance/move-tools pull request #155
Opened 2020-12-15 13:36 UTC by borispovod

* Supports ss58 address.
* Choose different dialects using dove (using manifest or -d/--dialect), e.g.:
`dove new -d polkadot tst`
* Manifest deserialize/serialize address as string now, later i use dialect to get real account address

2020-12-17 13:21 UTC, RIg410 approved these changes

2020-12-17 13:38 UTC, fzzr- requested changes

2020-12-17 13:38 UTC, fzzr- commented on dove/src/context.rs
> +        let acc_addr = self.manifest.package.account_address.clone().unwrap();
Will be great to remove that `unwrap` and return `Err` if cannot `clone`.

2020-12-17 13:38 UTC, fzzr- commented on dove/src/index/resolver/git.rs
> +            dialect.normalize_account_address(&manifest.package.account_address.unwrap())?;
Can we remove that `unwrap` and return `Err` if there's no `account_address`?

2020-12-17 13:38 UTC, fzzr- commented on lang/src/compiler/ss58.rs
> +        let item = mat.get(0).unwrap();
I know we unable return `Result` here now, but I do not recommend to use just `unwrap` without explicit explanation what is happen here. So, IMHO, will be better change `unwrap` to `expect("your error message")`.

2020-12-18 16:16 UTC, borispovod commented
don't merge and check it yet, want to write few tests, almost done

2020-12-18 17:16 UTC, borispovod commented
now it's ready for review :)

2020-12-21 06:35 UTC, fzzr- approved these changes
LGTM 👍
Thanks for the tests!

2020-12-21 06:36 UTC, merged